FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
PATH="$(brew --prefix python)/libexec/bin:${PATH}"
PATH="$(brew --prefix bash)/bin:${PATH}"

# setup asdf
ASDF_FORCE_PREPEND=yes
source $(brew --prefix asdf)/libexec/asdf.sh
