FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
PATH="$(brew --prefix python)/libexec/bin:${PATH}"
PATH="$(brew --prefix bash)/bin:${PATH}"

# setup asdf
ASDF_FORCE_PREPEND=yes
source $(brew --prefix asdf)/libexec/asdf.sh

# Created by `pipx` on 2024-05-26 11:54:15
export PATH="$PATH:/Users/corintho/.local/bin"
