{
  config,
  lib,
  pkgs,
  ...
}:

let
  # On macOS the daemon/agent runs directly under launchd (no login shell), so
  # shell-scoped sessionVariables never reach it. Pinning the vars on the plist
  # of the emacs LaunchAgent (generated by services.emacs) makes them race-free.
  doomEnv = {
    EMACSDIR = "${config.xdg.configHome}/emacs";
    DOOMDIR = "${config.xdg.configHome}/doom";
    DOOMLOCALDIR = "${config.xdg.dataHome}/doom";
    DOOMPROFILELOADFILE = "${config.xdg.stateHome}/doom-profiles-load.el";
  };
in
{
  launchd.agents.emacs.config = lib.mkIf config.services.emacs.enable {
    EnvironmentVariables = doomEnv;
    LimitLoadToSessionType = "Aqua";
  };
}
