{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  # On macOS the daemon/agent runs directly under launchd (no login shell), so
  # shell-scoped sessionVariables never reach it. Pinning the vars on the plist
  # of the emacs LaunchAgent (generated by services.emacs) makes them race-free.
  spacemacsEnv = {
    EMACSDIR = "${config.xdg.configHome}/emacs";
    SPACEMACSDIR = "${config.xdg.configHome}/spacemacs";
    NIX_SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
    SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
    PATH = lib.concatStringsSep ":" [
      "${config.home.homeDirectory}/.nix-profile/bin"
      "/etc/profiles/per-user/${config.home.username}/bin"
      "/run/current-system/sw/bin"
      "/nix/var/nix/profiles/default/bin"
      "/usr/bin"
      "/bin"
      "/usr/sbin"
      "/sbin"
    ];
  };

  # Emacs client launcher .app bundle for macOS. Provides a Spotlight/Raycast-
  # launchable shortcut to open a new Emacs frame via emacsclient.
  emacsPackage = if pkgs.stdenv.isLinux then pkgs.emacs-pgtk else pkgs.emacs;

  # Generate a Spacemacs .icns from the repo's SVG artwork: SVG -> PNG (rsvg)
  # -> .icns (icnsify). The bundle references the icon by its bare name.
  spacemacsIcon = pkgs.runCommand "spacemacs.icns" { } ''
    ${pkgs.librsvg}/bin/rsvg-convert -w 1024 -h 1024 -o icon.png ${inputs.spacemacs}/assets/spacemacs.svg
    mkdir -p $out
    ${pkgs.icnsify}/bin/icnsify -o $out/Spacemacs.icns icon.png
  '';

  emacsClientApp = pkgs.stdenv.mkDerivation {
    name = "EmacsClient";
    buildInputs = [ emacsPackage ];
    phases = [ "installPhase" ];
    installPhase = ''
      APP=$out/Applications/EmacsClient.app/Contents
      mkdir -p $APP/MacOS $APP/Resources

      # Shell script launcher: connect to running daemon, or start Emacs if needed
      cat > $APP/MacOS/EmacsClient << 'LAUNCHER'
      #!/bin/sh
      exec ${emacsPackage}/bin/emacsclient -c -a ""
      LAUNCHER
      chmod +x $APP/MacOS/EmacsClient

      # Copy Spacemacs icon into the bundle
      cp ${spacemacsIcon}/Spacemacs.icns \
         $APP/Resources/EmacsClient.icns

       # Minimal Info.plist for macOS app bundle
       cat > $APP/Info.plist << 'PLIST'
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>en</string>
        <key>CFBundleExecutable</key>
        <string>EmacsClient</string>
        <key>CFBundleIconFile</key>
        <string>EmacsClient</string>
        <key>CFBundleIdentifier</key>
        <string>org.gnu.emacsclient</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>EmacsClient</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>1.0</string>
        <key>CFBundleVersion</key>
        <string>1</string>
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
      </dict>
      </plist>
      PLIST
    '';
  };
in
{
  home.packages = lib.mkIf config.services.emacs.enable [ emacsClientApp ];

  launchd.agents.emacs = lib.mkIf config.services.emacs.enable {
    domain = "gui";
    config = {
      EnvironmentVariables = spacemacsEnv;
      KeepAlive = lib.mkForce true;
      LimitLoadToSessionType = "Aqua";
    };
  };
}
